CREATE DATABASE keycloak;

CREATE USER keycloak WITH ENCRYPTED PASSWORD 'keycloak';

GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;

\c keycloak;

GRANT ALL ON SCHEMA public TO keycloak;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO keycloak;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO keycloak;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO keycloak;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON SEQUENCES TO keycloak;

\c postgres;

CREATE DATABASE schooldb;

CREATE USER school WITH ENCRYPTED PASSWORD 'school';

GRANT ALL PRIVILEGES ON DATABASE schooldb TO school;

\c schooldb;

GRANT ALL ON SCHEMA public TO school;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO school;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO school;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO school;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON SEQUENCES TO school;